
spring:

  data:
    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: admin
#      username: admin
#      password: 123456
#      authentication-database: admin
      uri: mongodb://admin:123456@127.0.0.1:27017/javadb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


