
server:
  port: 8380

spring:
  application:
    name: springboot-integrate-mongodb
  
  # 数据库配置 - 使用统一MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/my-generated-db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  
  # MongoDB配置（保留原有功能）
  data:
    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: admin
#      username: admin
#      password: 123456
#      authentication-database: admin
      uri: mongodb://admin:123456@127.0.0.1:27017/javadb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


