server:
  port: 8280

spring:
  application:
    name: springboot-example-jpa
  
  datasource:
    # 使用统一的MySQL数据库
    url: jdbc:mysql://localhost:3306/my-generated-db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # 自动创建更新表结构
    hibernate:
      ddl-auto: update
    # 显示SQL语句
    show-sql: true
    # 格式化SQL语句
    properties:
      hibernate:
        format_sql: true
        # 启用二级缓存
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        # 统计信息
        generate_statistics: true
        # 缓存配置文件路径
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  
  # 缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  
  # H2控制台配置移除

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace